### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by GaurangShukla** [LuisReinoso/covid-19-community-tracker#11]
Hi! Can you please tell me what did you use here

namespace: 'sdjskaldjsakldjsakdldsajlkdjsalk', // valid GUID
  api: 'https://mycloudfunctionsapi.com',

What is the namespace and what api did you used. Thanks in advance.

**Comment by LuisReinoso** [comment]
Hi @GaurangShukla I create a valid GUID using this:
https://duckduckgo.com/?q=generator+GUID&t=ffab&ia=answer on duckduckgo or
https://guidgenerator.com/online-guid-generator.aspx

Why we need this. It's the seed to generate the fingerprint for other users:
Here is the line that I use it.
https://github.com/LuisReinoso/covid-19-community-tracker/blob/master/src/app/guid.service.ts#L49
